//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystems.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public int Id { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public Nullable<bool> ActionResult { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Users Users { get; set; }
    }
}
