//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementSystems.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryManagementSystemEntities : DbContext
    {
        public LibraryManagementSystemEntities()
            : base("name=LibraryManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Activities> Activities { get; set; }
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Case> Case { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Penalties> Penalties { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Annotations> Annotations { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
    
        public virtual ObjectResult<string> AuthorWithMostBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AuthorWithMostBooks");
        }
    
        public virtual ObjectResult<string> BestBook()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestBook");
        }
    
        public virtual ObjectResult<string> BestEmployee()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestEmployee");
        }
    
        public virtual ObjectResult<string> MostActiveMember()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MostActiveMember");
        }
    
        public virtual ObjectResult<string> AuthorWithMostBooks1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("AuthorWithMostBooks1");
        }
    
        public virtual ObjectResult<string> BestBook1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestBook1");
        }
    
        public virtual ObjectResult<string> BestEmployee1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("BestEmployee1");
        }
    
        public virtual ObjectResult<string> MostActiveMember1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MostActiveMember1");
        }
    }
}
